### ISSUE TITLE
typo on expiration value 

### ISSUE THREAD

**Issue by sheecet** [tursodatabase/turso-api-client-ts#14]
there is typo on expiration value on this page:

https://www.npmjs.com/package/@tursodatabase/api

  expiration: "1w2d6h3n",

should be

  expiration: "1w2d6h3m",

**Comment by notrab** [comment]
Feel free to open a pull request with the change, otherwise I’ll get to updating this tomorrow. Thank you 🙏

**Comment by notrab** [comment]
Updated and fixed, thank you 🙏🏻
